<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $electronics = Category::where('slug', 'electronics')->first();
        $smartphones = Category::where('slug', 'smartphones')->first();
        $laptops = Category::where('slug', 'laptops')->first();
        $fashion = Category::where('slug', 'fashion')->first();
        $men = Category::where('slug', 'men-fashion')->first();
        $women = Category::where('slug', 'women-fashion')->first();
        $home = Category::where('slug', 'home-living')->first();
        $furniture = Category::where('slug', 'furniture')->first();
        $beauty = Category::where('slug', 'beauty')->first();
        $skincare = Category::where('slug', 'skincare')->first();
        $sports = Category::where('slug', 'sports')->first();
        $fitness = Category::where('slug', 'fitness')->first();

        $products = [
            // Smartphones
            [
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'description' => 'The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.',
                'short_description' => 'Most powerful iPhone with titanium design',
                'price' => 1199.00,
                'compare_price' => 1299.00,
                'category_id' => $smartphones->id,
                'sku' => 'IP15PM-256-BLK',
                'stock_quantity' => 50,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=iPhone+15+Pro',
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Premium Android flagship with S Pen, 200MP camera, and AI features.',
                'short_description' => 'Ultimate Android flagship with S Pen',
                'price' => 1299.00,
                'compare_price' => 1399.00,
                'category_id' => $smartphones->id,
                'sku' => 'SG24U-512-TIT',
                'stock_quantity' => 45,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=Galaxy+S24+Ultra',
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'AI-powered smartphone with best-in-class camera and Google AI features.',
                'short_description' => 'AI-powered smartphone with amazing camera',
                'price' => 999.00,
                'category_id' => $smartphones->id,
                'sku' => 'GP8P-128-OBS',
                'stock_quantity' => 30,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=Pixel+8+Pro',
            ],
            // Laptops
            [
                'name' => 'MacBook Pro 16" M3 Max',
                'slug' => 'macbook-pro-16-m3-max',
                'description' => 'Supercharged by M3 Max chip for unprecedented performance.',
                'short_description' => 'Powerful laptop with M3 Max chip',
                'price' => 3499.00,
                'compare_price' => 3699.00,
                'category_id' => $laptops->id,
                'sku' => 'MBP16-M3-36',
                'stock_quantity' => 25,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=MacBook+Pro',
            ],
            [
                'name' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'description' => 'Premium Windows laptop with stunning display and powerful performance.',
                'short_description' => 'Premium Windows laptop with 15.6" display',
                'price' => 1899.00,
                'category_id' => $laptops->id,
                'sku' => 'XPS15-I9-32',
                'stock_quantity' => 20,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=Dell+XPS+15',
            ],
            [
                'name' => 'HP Spectre x360',
                'slug' => 'hp-spectre-x360',
                'description' => '2-in-1 convertible laptop with stunning design and versatility.',
                'short_description' => '2-in-1 convertible laptop',
                'price' => 1599.00,
                'category_id' => $laptops->id,
                'sku' => 'SPCTRE-I7-16',
                'stock_quantity' => 15,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/1a1a1a/white?text=HP+Spectre',
            ],
            // Fashion - Men
            [
                'name' => 'Classic Cotton T-Shirt',
                'slug' => 'classic-cotton-tshirt',
                'description' => 'Premium quality cotton t-shirt perfect for everyday wear.',
                'short_description' => 'Comfortable cotton t-shirt',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => $men->id,
                'sku' => 'TSHIRT-COT-WHT',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/2563eb/white?text=Cotton+T-Shirt',
            ],
            [
                'name' => 'Slim Fit Jeans',
                'slug' => 'slim-fit-jeans',
                'description' => 'Modern slim fit jeans with stretch comfort.',
                'short_description' => 'Modern slim fit jeans',
                'price' => 79.99,
                'category_id' => $men->id,
                'sku' => 'JEANS-SLM-BLU',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/2563eb/white?text=Slim+Jeans',
            ],
            [
                'name' => 'Casual Blazer',
                'slug' => 'casual-blazer',
                'description' => 'Versatile blazer for both casual and formal occasions.',
                'short_description' => 'Versatile casual blazer',
                'price' => 199.99,
                'compare_price' => 249.99,
                'category_id' => $men->id,
                'sku' => 'BLAZER-NVY',
                'stock_quantity' => 50,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/2563eb/white?text=Casual+Blazer',
            ],
            // Fashion - Women
            [
                'name' => 'Summer Floral Dress',
                'slug' => 'summer-floral-dress',
                'description' => 'Beautiful floral print dress perfect for summer occasions.',
                'short_description' => 'Beautiful floral print dress',
                'price' => 89.99,
                'compare_price' => 119.99,
                'category_id' => $women->id,
                'sku' => 'DRESS-FLR-PNK',
                'stock_quantity' => 75,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/db2777/white?text=Floral+Dress',
            ],
            [
                'name' => 'High-Waist Pants',
                'slug' => 'high-waist-pants',
                'description' => 'Elegant high-waist pants for professional look.',
                'short_description' => 'Elegant high-waist pants',
                'price' => 69.99,
                'category_id' => $women->id,
                'sku' => 'PANTS-HW-BLK',
                'stock_quantity' => 80,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/db2777/white?text=High+Waist+Pants',
            ],
            // Home & Furniture
            [
                'name' => 'Modern Sofa Set',
                'slug' => 'modern-sofa-set',
                'description' => 'Elegant 3-seater modern sofa with premium fabric.',
                'short_description' => 'Elegant 3-seater modern sofa',
                'price' => 1299.00,
                'compare_price' => 1599.00,
                'category_id' => $furniture->id,
                'sku' => 'SOFA-MOD-3ST',
                'stock_quantity' => 10,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1f2937/white?text=Modern+Sofa',
            ],
            [
                'name' => 'Oak Dining Table',
                'slug' => 'oak-dining-table',
                'description' => 'Beautiful solid oak dining table for 6 people.',
                'short_description' => 'Solid oak dining table',
                'price' => 899.00,
                'category_id' => $furniture->id,
                'sku' => 'TABLE-OAK-6P',
                'stock_quantity' => 8,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/1f2937/white?text=Oak+Table',
            ],
            [
                'name' => 'Comfort King Bed',
                'slug' => 'comfort-king-bed',
                'description' => 'Luxury king size bed with orthopedic mattress.',
                'short_description' => 'Luxury king size bed',
                'price' => 2499.00,
                'compare_price' => 2999.00,
                'category_id' => $home->id,
                'sku' => 'BED-KING-LUX',
                'stock_quantity' => 5,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/1f2937/white?text=King+Bed',
            ],
            // Beauty
            [
                'name' => 'Anti-Aging Serum',
                'slug' => 'anti-aging-serum',
                'description' => 'Powerful vitamin C serum for radiant skin.',
                'short_description' => 'Vitamin C serum for radiant skin',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => $skincare->id,
                'sku' => 'SERUM-VITC-30',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/f472b6/white?text=Vitamin+C+Serum',
            ],
            [
                'name' => 'Hydrating Moisturizer',
                'slug' => 'hydrating-moisturizer',
                'description' => 'Deep hydration moisturizer for all skin types.',
                'short_description' => 'Deep hydration moisturizer',
                'price' => 49.99,
                'category_id' => $skincare->id,
                'sku' => 'MOIST-HYD-50',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/f472b6/white?text=Hydrating+Moisturizer',
            ],
            // Sports
            [
                'name' => 'Pro Yoga Mat',
                'slug' => 'pro-yoga-mat',
                'description' => 'Premium non-slip yoga mat with carrying strap.',
                'short_description' => 'Premium non-slip yoga mat',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => $fitness->id,
                'sku' => 'YOGA-MAT-PRO',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/16a34a/white?text=Yoga+Mat',
            ],
            [
                'name' => 'Adjustable Dumbbells',
                'slug' => 'adjustable-dumbbells',
                'description' => 'Space-saving adjustable dumbbells 5-50 lbs.',
                'short_description' => 'Space-saving adjustable dumbbells',
                'price' => 399.00,
                'category_id' => $fitness->id,
                'sku' => 'DUMB-ADJ-50',
                'stock_quantity' => 30,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/16a34a/white?text=Adjustable+Dumbbells',
            ],
            [
                'name' => 'Running Shoes Pro',
                'slug' => 'running-shoes-pro',
                'description' => 'Professional running shoes with advanced cushioning.',
                'short_description' => 'Professional running shoes',
                'price' => 149.99,
                'compare_price' => 179.99,
                'category_id' => $sports->id,
                'sku' => 'SHOES-RUN-PRO',
                'stock_quantity' => 80,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'https://placehold.co/600x400/16a34a/white?text=Running+Shoes',
            ],
            [
                'name' => 'Fitness Tracker Watch',
                'slug' => 'fitness-tracker-watch',
                'description' => 'Advanced fitness tracker with heart rate monitor.',
                'short_description' => 'Advanced fitness tracker',
                'price' => 199.99,
                'category_id' => $sports->id,
                'sku' => 'TRACK-FIT-PRO',
                'stock_quantity' => 60,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'https://placehold.co/600x400/16a34a/white?text=Fitness+Tracker',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
